### ISSUE TITLE
Indy client has 10 second delay when upgrading from Delphi 10.2 to 10.4

### ISSUE THREAD

**Issue by pmanion** [IndySockets/Indy#374] opened 2021-08-16 17:24 UTC
Our company develops a Point of Sale system that supports various credit card transaction providers. It has a JavaScript web client front end and a Delphi server back end. It uses Indy 10 heavily for HTTP communication.

One of our platforms we support is Adyen. I have developed a plugin that uses Indy 10's HTTP client to connect to an Adyen EFT device running a server which performs credit card transactions, communicating with a back end server on the WWW. I have this working reliably in Delphi 10.2. This year we upgraded to Delphi 10.4, and I find that there is now a considerable delay in the response time of Indy 10 requests to the device, on the order of 10 seconds per request.

Using the OnWorkBegin, OnWork and OnWorkEnd events (with handler methods named HTTPWorkBegin, HTTPWork, and HTTPWorkEnd respectively), I was able to log the timing of the request in Delphi 10.4. From this I discovered that a 10 second delay (nearly to the millisecond) occurs on the request read between the end of the HTTPWork method and the beginning of the HTTPWorkEnd method.

2021.08.12.16.13.36.889  [  5940] +Info  | https://10.50.100.53:8443/nexo/
2021.08.12.16.13.36.890  [  5940] +Info  | POST begin
2021.08.12.16.13.38.904  [  5940] >Enter | TAdyenDisplay.HTTPWorkBegin
2021.08.12.16.13.38.930  [  5940] @Debug | WorkMode = Write; WorkCountMax = 1146
2021.08.12.16.13.38.931  [  5940] <Exit  | TAdyenDisplay.HTTPWorkBegin
2021.08.12.16.13.38.932  [  5940] >Enter | TAdyenDisplay.HTTPWork
2021.08.12.16.13.38.933  [  5940] @Debug | WorkMode = Write; WorkCount = 1146
2021.08.12.16.13.38.933  [  5940] <Exit  | TAdyenDisplay.HTTPWork
2021.08.12.16.13.38.934  [  5940] >Enter | TAdyenDisplay.HTTPWorkEnd
2021.08.12.16.13.38.935  [  5940] @Debug | WorkMode = Write
2021.08.12.16.13.38.936  [  5940] <Exit  | TAdyenDisplay.HTTPWorkEnd
2021.08.12.16.13.39.221  [  5940] >Enter | TAdyenDisplay.HTTPWorkBegin
2021.08.12.16.13.39.222  [  5940] @Debug | WorkMode = Read; WorkCountMax = 0
2021.08.12.16.13.39.223  [  5940] <Exit  | TAdyenDisplay.HTTPWorkBegin
2021.08.12.16.13.39.223  [  5940] >Enter | TAdyenDisplay.HTTPWork
2021.08.12.16.13.39.224  [  5940] @Debug | WorkMode = Read; WorkCount = 973
2021.08.12.16.13.39.225  [  5940] <Exit  | TAdyenDisplay.HTTPWork
   ---ten second delay--
2021.08.12.16.13.49.220  [  5940] >Enter | TAdyenDisplay.HTTPWorkEnd
2021.08.12.16.13.49.221  [  5940] @Debug | WorkMode = Read
2021.08.12.16.13.49.222  [  5940] <Exit  | TAdyenDisplay.HTTPWorkEnd
2021.08.12.16.13.49.223  [  5940] +Info  | POST end
2021.08.12.16.13.49.223  [  5940] +Info  | Elapsed Time: 12 seconds

Comparing this to the same request running in Delphi 10.2, the log indicates no delay:

2021.08.13.17.24.40.916   [9724]    Information    https://10.50.100.53:8443/nexo/
2021.08.13.17.24.40.917   [9724]    Information    POST begin
2021.08.13.17.24.42.373   [9724]    >> Entry >>    TAdyenDisplay.HTTPWorkBegin
2021.08.13.17.24.42.373   [9724]    Information    WorkMode = Write; WorkCountMax = 1146
2021.08.13.17.24.42.374   [9724]    << Exit  <<    TAdyenDisplay.HTTPWorkBegin
2021.08.13.17.24.42.374   [9724]    >> Entry >>    TAdyenDisplay.HTTPWork
2021.08.13.17.24.42.375   [9724]    Information    WorkMode = Write; WorkCount = 1146
2021.08.13.17.24.42.375   [9724]    << Exit  <<    TAdyenDisplay.HTTPWork
2021.08.13.17.24.42.376   [9724]    >> Entry >>    TAdyenDisplay.HTTPWorkEnd
2021.08.13.17.24.42.376   [9724]    Information    WorkMode = Write
2021.08.13.17.24.42.377   [9724]    << Exit  <<    TAdyenDisplay.HTTPWorkEnd
2021.08.13.17.24.42.506   [9724]    >> Entry >>    TAdyenDisplay.HTTPWorkBegin
2021.08.13.17.24.42.507   [9724]    Information    WorkMode = Read; WorkCountMax = 0
2021.08.13.17.24.42.508   [9724]    << Exit  <<    TAdyenDisplay.HTTPWorkBegin
2021.08.13.17.24.42.559   [9724]    >> Entry >>    TAdyenDisplay.HTTPWork
2021.08.13.17.24.42.559   [9724]    Information    WorkMode = Read; WorkCount = 975
2021.08.13.17.24.42.560   [9724]    << Exit  <<    TAdyenDisplay.HTTPWork
  --no significant delay--
2021.08.13.17.24.42.561   [9724]    >> Entry >>    TAdyenDisplay.HTTPWorkEnd
2021.08.13.17.24.42.561   [9724]    Information    WorkMode = Read
2021.08.13.17.24.42.562   [9724]    << Exit  <<    TAdyenDisplay.HTTPWorkEnd
2021.08.13.17.24.42.562   [9724]    Information    POST end
2021.08.13.17.24.42.563   [9724]    Information    Elapsed Time: 1 seconds

I am baffled what could be the difference. Any ideas would be appreciated.

**Comment by rlebeau** [comment] 2021-08-16 20:45
I don't recall any changes made to Indy between Delphi 10.2 and 10.4 (and there have been many!) that should account for such a delay. If anything, Indy should be running a little faster, not slower. It would help to see a capture of the raw TCP/HTTP traffic w/ timestamps to isolate the actual socket I/O operation that is lagging. The OnWork events alone are not fine-grain enough to determine the root cause.

**Comment by pmanion** [comment] 2021-08-16 20:49
The fact that the delay is so specific (exactly 10 seconds, give or take a few milliseconds) is peculiar.  It made me wonder if there is some delay setting that was introduced in Delphi 10.4 that I was unaware of.

Regardless, I will try to debug the problem in Wireshark to see if that gives me any clues.

**Comment by rlebeau** [comment] 2021-08-16 20:52
> It made me wonder if there is some delay setting that was introduced in Delphi 10.4 that I was unaware of.

Not that I know of.

Do you have a 10-second `ReadTimeout` assigned to `TIdHTTP`?  Maybe it is blocked thinking there is more data to read when there really is not?

**Comment by pmanion** [comment] 2021-09-03 17:23
After working on another project for a while, I've finally had a chance to resume debugging this problem.  It seems to be a problem between Indy 10 and the Adyen EFT platform's Terminal API, which uses an implementation of the 'nexo'  standard (defined at www.nexo-standards.org).

Our company's Point of Sale software integrates with the Adyen EFT platform by posting payment and item display requests to the 'nexo' URL of the payment device (e.g., Verifone) running the Adyen software.  We use the Indy 10 TIdHTTP client to make these requests.  Once we upgraded Delphi from 10.2 to 10.4, we started noticing the long delays.

To isolate the problem, I've written a standalone Delphi application that uses Indy HTTP Client to POST the JSON payload to a Verifone device running Adyen's platform software.  The response is an answering JSON payload.  The program displays the start time, end time, and elapsed time of POST requests.

When compiled under Delphi 10.2, the response time is one second or less; when compiled under 10.4, the 10 second delay occurs.  The delay is entirely on the Adyen side, as the HTTP client waits for a response.  This is puzzling, because clearly the difference between the two requests is the version of the HTTP Client in use.  What could cause the same request to be delayed at the server end, simply by changing the code in the client?

I even tried observing the problem in Wireshark, filtering on the TCP traffic between the requesting computer and the Adyen device.  I have file captures of each request from the two test application compilations, which I wished to attach here, but they are in PCapNG format, which GitHub doesn't support.  But the data captures affirmed that no TCP traffic passes between the two during the 10 second delay.

I also intend to report this issue to Adyen's tech support team.  

Please advise as to the next step.  I will see if I can post the Wireshark data captures in another format.

**Comment by pmanion** [comment] 2021-09-03 20:39
Here are the two Wireshark data captures as text files:

[Delphi 10.2 - Adyen Nexo TXN.txt](https://github.com/IndySockets/Indy/files/7108392/Delphi.10.2.-.Adyen.Nexo.TXN.txt)
[Delphi 10.4 - Adyen Nexo TXN.txt](https://github.com/IndySockets/Indy/files/7108393/Delphi.10.4.-.Adyen.Nexo.TXN.txt)

**Comment by rlebeau** [comment] 2021-09-07 17:42
There have been a handful of bug fixes/updates to TIdHTTP between Delphi 10.2 and 10.4, but nothing that would account for this delay, I think.  And since the traffic is HTTPS, Wireshark can't show the decoded HTTP requests.  So, to see if there are any differences in the HTTP requests, you can attach a `TIdConnectionIntercept`-derived component, such as one of Indy's `TIdLog...` component, to the `TIdHTTP.Intercept` property.

**Comment by pmanion** [comment] 2021-09-15 16:46
I made a rather baffling discovery regarding this problem with Adyen.  I modified the standalone test application to remove the Indy 10 client altogether and replace it with the Ararat Synapse client THTTPSend (found at www.ararat.cz/synapse), and discovered that I have the exact same 10 second delay in the POST response from the Adyen device.  So to sum up my observations:

Delphi 10.2 with Indy 10:  0-1 second delay response from POST to Adyen device
Delphi 10.4 with Indy 10: 10 second delay
Delphi 10.4 with Ararat Synapse: 10 second delay

So the obvious next test, I suppose, is to try Synapse with 10.2, if that's a feasible option.  And I'm still trying to get tech support from Adyen.  But in the meantime I'm rather baffled by these results.  Any ideas?

**Comment by rlebeau** [comment] 2021-09-15 20:15
Well, clearly the issue is with the Adyen device, but there is simply not enough diagnostics presented here to figure out what is happening.  As mentioned earlier, I would still want to see the actual HTTP requests being made in 10.2 and 10.4, from Indy and now Synapse, to see if there are any differences in the requests that might be triggering the delay.  I already described how you can get that HTTP data in Indy without regard to TLS encryption.  Synapse has a similar way of getting the same data - assign a handler to the `THTTPSend.Sock.OnMonitor` event.

**Comment by pmanion** [comment] 2021-09-15 22:34
The fact is the request traffic is not actually encrypted over the wire.  The nexo protocol is to take an unencrypted payload in JSON, encrypt it with CBC encryption, encode the binary in Base64, and then insert it into the "NexoBlob" node of a new JSON payload. That way the traffic is visible over the wire but the customer information portion is secure.  The response payload contains its own NexoBlob, which is unencrypted via CBC to create the response JSON to the application.

So the HTTP POST request looks like this:

URL with IP address and port of Adyen device:
https://10.50.100.53:8443/nexo/

JSON payload:
{
	"SaleToPOIRequest": {
		"MessageHeader": {
			"ServiceID": "GKTZ1X4XAH",
			"ProtocolVersion": "3.0",
			"MessageClass": "Device",
			"POIID": "M400-401659528",
			"MessageType": "Request",
			"SaleID": "RetailProProxy",
			"MessageCategory": "Display"
		},
		"NexoBlob": "H7BaSBESL0s3slEpIN2umeT3krST/anCtspcNqj6Y/rViHGylbmukOmOyHptI+GtUuzw1F0rcBosEbGm5yQ104kHno/+ubF7L8Map79WCpgmpYrD+ReoVSU72jTqcnmaY8KcCZmDqY0xbfPAZ4jswiXXfC0FY7f3WS7HmNYUpxgycqrHusEbfb86gF2we7l55X3Z+w/KXoSUvvjQZAO+AWQxw4xUIWTGYXW1wSJYIrCxXEdTvzJCWKMVoU6Jl95pvSlXzOe2z3PNFpLETCV6T47oywHc9QYvByZSTi+OAWnIvH1dgopmCJJ+o6xx1n8x57Q4U1ssqYYv3UV0JbkbH7YwZUDrcMLZCrIM0sGJY4Gu8x6aUWETmoRBHzJVOpRLRjdMk4/UrQXH+falO2h6K+szAWXOQOz2iVwFn+DfiwKObV74DDrlQiblQEBj3BVUlgH7RY75GsfkVMUsJjXSP5BPWu2RREKm8heTymL6HtxGO1POcZkmhIJSZJ6DIYUFXvXLVM8EJCP2ScsEQjsi/etQiQ+6pXGkZ2p4/OMaxAWQm9E6Rsrn9lmW/jyaYecw7/TJ9kydhDATskslvd6cM6lYYclsEuFQX9hIFOL0c8kRWQlSBSwG2Q6M25tU5SXRC7ZWjg/20Sdz755v3OMJt7QSqSOh3aI0M3Twa1wjcgRl7TaIJkHPxDMh9q5Fpsgz7cD8XvtYZwD6T38dCfL61Q==",
		"SecurityTrailer": {
			"Hmac": "WVTrZfZVydLdSWmaatiRKwpyhzPrdURMUwduu+TL4W8=",
			"KeyIdentifier": "RetailProPrismPOSAdyen",
			"KeyVersion": 0,
			"AdyenCryptoVersion": 1,
			"Nonce": "1ZKIDlcOAmqi1aNdRaGhxg=="
		}
	}
}

And a typical response payload:

{
	"SaleToPOIResponse": {
		"MessageHeader": {
			"MessageCategory": "Display",
			"MessageClass": "Device",
			"MessageType": "Response",
			"POIID": "M400-401659528",
			"ProtocolVersion": "3.0",
			"SaleID": "RetailProProxy",
			"ServiceID": "GKTZ1X4XAH"
		},
		"NexoBlob": "dNIaPyNZcsJxAh0LjXITWeX\/E\/mrvQsJL8XBMLWdl7UTVCHw2Sj5E\/69F0jpKngfMAR2gA9e6EjkAdNXa9O36dEu9hInI8nfIMM1v42XVqD2fq920znvW9\/kN+Fz0uvJcpcUuJ6g4h\/699L3ufAkZS+\/MBYBeNpefT+svWvTXL0hUfHa7kRU2wwqzhjoqmUYrpNT9YMY\/DQHxoB4+v0OTkg0O\/GKWRqM1zr3dtcWH7RnAkLaGtM0pUtbGgxzS91XuE4R6Y+GbxI66qi4GbLiQbgo15P1hmaBqP+rAnRMGOLjj7L+1+1tY3mdcvEqhGEGlmzGCQjnQk5wkHbF7QNL1MH1v3qRMAMX4F+cqSpFRh2G20yUk8Ki9OvIJtroP5IjrVhuDNjK5Gvq1KSchxwLmH02dg6UAlFYr3yiUCV3M4QPjZ\/0zKh9cMQoLI1WH04MfT7ZaQsSWkVDInftSCocNUI\/1\/TD8dDrmO0+PHpH50uyyWFlgI9n1vqE6z4It0RThmdjlVgDwh8+xEeyqyxRE8kcIXauUmt30+bFTZX4JmOoWM5ISJdqmenvDM2EaWylqXwW\/TxxeT8wP4j7y+hj1UTtc7H\/2nnzEawix7dHHaRYD+fthA4uXqE4Q5od6QXC6kQ\/BLY4JbObfbI97cuVEYZx8odZUbO1\/\/Qw5RX3e7s=",
		"SecurityTrailer": {
			"AdyenCryptoVersion": 1,
			"Hmac": "l2Sc4ZSmRfYHy12OGEh1egcbAgQKLPObNyR41UyeHCw=",
			"KeyIdentifier": "RetailProPrismPOSAdyen",
			"KeyVersion": 0,
			"Nonce": "EB9qeBejdqJ08mlnq1PPMA=="
		}
	}
}

I use the exact same request payload for every test.  The response payload varies in the NexoBlob field, but is otherwise the same.

**Comment by rlebeau** [comment] 2021-09-16 16:01
> The fact is the request traffic is not actually encrypted over the wire.

It should be, since it is being accessed via an HTTPS url.  HTTPS uses TLS encryption on the wire.

> So the HTTP POST request looks like this:

That info doesn't include the HTTP request/response headers, which are also important, not just the payload.  Unless the delay is being caused by JSON processing, I don't need the details of the JSON itself.

Something else I just thought of - does the HTTP "Date" response header include the delay time?  That could help in diagnosing whether the delay is in the generation of the response itself, or just in the transmission of the response.

**Comment by pmanion** [comment] 2021-09-17 00:07
I can confirm that the Date header does NOT include the delay.  Example of TIdHTTP Request under Delphi 10.4:

HTTP POST 
Start time: 9/16/2021 5:02:45 PM

Response headers:
Date: Fri, 17 Sep 2021 00:02:46 GMT
Connection: keep-alive
Server: Adyen/webserver
Content-type: application/json; charset=utf-8

Finish time: 9/16/2021 5:02:56 PM

So the 10 second delay is absent from the response header, but the return from the HTTP POST call has the delay.  What may this signify?

**Comment by pmanion** [comment] 2021-09-17 01:28
I found a difference in the headers between the non-delay and delay case.  

In Indy 10 under 10.2, the response headers are:

Date: Fri, 17 Sep 2021 01:24:10 GMT
**Connection: close**
Server: Adyen/webserver
Content-type: application/json; charset=utf-8

Whereas under 10.4 they are:

Date: Fri, 17 Sep 2021 01:24:11 GMT
**Connection: keep-alive**
Server: Adyen/webserver
Content-type: application/json; charset=utf-8

So the difference is Connection close vs. keep-alive.  And in the case of the Synapse requests, on both Delphi versions they use Connection keep-alive as well.  Could this be the determining factor?

**Comment by rlebeau** [comment] 2021-09-17 20:34
> So the 10 second delay is absent from the response header, but the return from the HTTP POST call has the delay. What may this signify?

It signifies that the Adyen took 10 seconds to transmit the HTTP response after creating it.

> So the difference is Connection close vs. keep-alive.

You didn't show the requests, though.  Perhaps the 10.2 client requested no keep-alive, whereas the 10.4 client did.  But in any case, handling of the TCP connection should not affect the timing of the transmissions.  Unless there is a bug in Adyen's implementation when keep-alives are used.

> And in the case of the Synapse requests, on both Delphi versions they use Connection keep-alive as well.

Was the delay present when using Synapse in 10.2?  You've only stated so far that the delay is present under 10.4, you hadn't mentioned the result of testing Synapse in 10.2 yet.

**Comment by pmanion** [comment] 2021-09-17 20:42
I forgot to mention the other Synapse test.  It also has the delay in 10.2.  So the only combination with no delay was Indy under 10.2.

The reason I hadn't posted the request headers is because I couldn't find them at first.  I just drilled down to where they are being assigned in the Request.SetHeaders method in IdHTTP.

This is the request header list for Indy/10.4:

Connection: keep-alive
Content-Length: 1146
Host: 10.50.100.53:8443
Accept: text/json
User-Agent: Mozilla/3.0 (compatible; Indy Library)

I will dig up the other combinations next.

Also I tried to set the request connection to 'close' but perhaps I used the wrong syntax.  I will try your example as well.

**Comment by rlebeau** [comment] 2021-09-17 20:47
> The reason I hadn't posted the request headers is because I couldn't find them at first.

I told you in [this reply](https://github.com/IndySockets/Indy/issues/374#issuecomment-914498588) how you can access the HTTP request/response data that is being transmitted back and forth.  No need to go digging through the code.

**Comment by pmanion** [comment] 2021-09-17 20:48
> simply set TIdHTTP.Request.Connection := 'close'; and see if the delay goes away.
It worked! I had the right idea but the wrong syntax.  I think this is the answer.

**Comment by rlebeau** [comment] 2021-09-17 20:50
Well, now you have something to tell Adyen's support - their keep-alive handling is causing delayed responses.

**Comment by pmanion** [comment] 2021-09-17 20:54
Exactly! Let me do some more tests.  If all is OK I think we can close this issue.

**Comment by pmanion** [comment] 2021-09-17 20:58
I just tested fixing Synapse by setting its KeepAlive property to False.  This also results in Connection close and no delay.

**Comment by pmanion** [comment] 2021-09-17 21:00
I think I'm good to go.  Thank you for all your help.  It was greatly appreciated.

**Closed** 2021-09-17 21:23 UTC
Labels: bug, TCP Clients/Servers, Compiler/IDE
