### ISSUE TITLE
Is there a way to access the documentation for indyproject?

### ISSUE THREAD

**Issue by AnthonySWest** [IndySockets/Indy#541] opened 2024-08-09 23:54 UTC
I am trying to download the documentation from page:

indyproject.org/documentation/

Clicking on any of the documentation links results in the following error (in FireFox):

```
Hmm. We’re having trouble finding that site.

We can’t connect to the server at ww2.indyproject.org.

If you entered the right address, you can:

    Try again later
    Check your network connection
    Check that Firefox has permission to access the web (you might be connected but behind a firewall)
```

Bad link, or site down? I have tried a few times throughout this week.

**Comment by rlebeau** [comment] 2024-08-10 03:49
https://www.indyproject.org/2021/02/10/links-to-old-indy-website-pages-are-currently-broken/

**Comment by rlebeau** [comment] 2024-08-10 03:51
Duplicate of #515

**Closed by rlebeau** 2024-08-10 03:51 UTC
Labels: Type: Question, Status: Reported

**Comment by jachguate** [comment] 2024-08-10 07:24
I have uploaded a copy I found locally of the documentation to github at
https://github.com/jachguate/indydocs

The same documentation is accessible online here:
https://jachguate.github.io/indydocs/html/

Juan Antonio Castillo H. (jachguate)
Blog: http://jachguate.wordpress.com

**Comment by AnthonySWest** [comment] 2024-08-10 15:40
Thanks!
