### ISSUE TITLE
Wince TCPInfoEx undefined and  runtime Range check errors

### ISSUE THREAD

**Issue by abebuch** [IndySockets/Indy#298] opened 2020-04-23 17:28 UTC
Hi,

lazaruz 2.0.1  
fpc 3.3.1 
Wince cross compile

Compiling indyLaz 106.2 gives an error undefined TCPInfoEx
so i surrounded them with   {$IFNDEF HAS_GetCPInfoEx} so it compiles now. (no idea if what i did is correct)

But as soon as i put a TidTCPclient component on a form and compile ( with debug uncheked, with debug on it wont compile complaining  exe size too big for wince.. ), running the program gives range check errors.

**Comment by rlebeau** [comment] 2020-04-27 16:23
FreePascal has a definition for `GetCPInfoEx()`, so it should also have a definition for `TCPInfoEx` as well.  Unless FreePascal uses a different name for it than Delphi does, or isn't defining it at all for WinCE.  I can't tell you if your "fix" is correct since you didn't actually show what you did.  It is important for `TIdMBCSEncoding.Create()` to use `GetCPInfoEx()`, so you can't just `{$IFDEF}` it out completely.  There is an `{$IFDEF WINDOWS}` block just above the implementation of `TIdMBCSEncoding.Create()` that is responsible for making sure `GetCPInfoEx()` is defined if it is not already defined by the compiler RTL, so a better solution is to update that block to handle your situation correctly, for instance by NOT defining `HAS_GetCPInfoEx` under WinCE, if that is what is needed.

As for the Range Check errors, you are going to have to be much more specific about those errors.  Where exactly are they occurring?

I don't have FreePascal installed to compile with, so I can't address your issues without specific details.

**Comment by abebuch** [comment] 2020-04-27 21:20
Hi,

looks like freepascal does not have a definition for GetCPInfoEx().
see system\idGlogal.pas line  2932  it reads // TODO: when was GetCPInfoEx() added to FreePascal?    
so i added a 
{$IFDEF WINCE}
  {$UNDEF HAS_GetCPInfoEx}
{$ENDIF}
just before line 2952 reading  {$IFNDEF HAS_GetCPInfoEx}
It compiles but it would not run. it shows an Error upon launch reading "The file project1.exe can not be opened. Either it is not signed with trusted certificate, or one of its components cannot be found..."

the project is an empty form with a TIDTCPServer on it

Thanks for looking into this.

**Comment by rlebeau** [comment] 2020-04-27 21:36
Does `GetCPInfoEx()` even exist on WinCE at all?

**Comment by abebuch** [comment] 2020-04-27 22:44
no clue. My knowledge in low level stuff is less then nil.
searching the Lazarus sources found it only in Indy & Jedi.

**Comment by Bi0T1N** [comment] 2020-04-28 11:33
> 
> 
> > looks like freepascal does not have a definition for GetCPInfoEx().
> 
> Yes, it does, or I wouldn't have put it in the code to begin with. But maybe it is just not defined for WinCE? Does `GetCPInfoEx(A|W)` even exist on WinCE at all? If not, then Indy will have to fallback to `GetCPInfo` instead.

WinCE seems to only know
```
wince/wininc/coredll.inc:function GetCPInfo(_para1:UINT; _para2:LPCPINFO):WINBOOL; external KernelDLL name 'GetCPInfo';
wince/wininc/redef.inc:function GetCPInfo(CodePage: UINT; var lpCPInfo: TCPInfo): BOOL;external KernelDLL name 'GetCPInfo';
```
which are inside the `wince/wininc`  folder while the other windows platforms declarations are defined in `win/wininc`.

**Comment by rlebeau** [comment] 2020-04-28 16:46
I wasn't asking if FreePascal knows about `GetCPInfoEx()` on WinCE.  Obviously it doesn't, or you wouldn't be getting compiler errors.  I was asking whether WinCE itself actually implements `GetCPInfoEx()` in `kernel32.dll` or not.  I don't have access to WinCE to check, and it is not documented on MSDN.

**Comment by rlebeau** [comment] 2020-04-28 17:15
I checked in an update for the GetCPInfoEx() issue.  But you still haven't mentioned where the range check errors are happening.

**Comment by abebuch** [comment] 2020-04-28 19:52
Ok now it compiles out of the box, But i get the range check error. 
The error happens just by dropping a TidtcpServer component on a for.  It errors at launching.

[FORMS.PP] ExceptionOccurred 
  Sender=EIdStackInitializationFailed
  Exception=Range check error
  Stack trace:
  $002561AC
  $002705C8
  $002699C4
  $00277E1C
  $00267034
  $00250C94
  $00277540
  $0005BDE4
  $0005C4A0
  $0005DE84
  $000F28EC
  $000F26EC
  $000F1680
  $00032488
  $0003232C
  $00035090
  $0003CC44
[FORMS.PP] ExceptionOccurred 
  Sender=ERangeError
  Exception=Range check error
  Stack trace:
  $00256150
  $0026C630
  $0026C828
  $0026C2F8
  $00274960
  $00023100

**Comment by rlebeau** [comment] 2020-04-28 20:50
Raw memory addresses in stack traces are useless, I would need to see the actual function names to know which functions are calling which functions.

As for `EIdStackInitializationFailed` specifically, there is only one place in Indy where that exception is raised - in `TIdStackWindows.Create()` if an `Exception` is caught while calling `InitializeWinSock()`, `IdWship6.InitLibrary()`, `IdIDN.InitIDNLibrary()`, or `InitializeIPHelperAPI()`.  But without see valid function names in the trace, there is simply no way for me to know which functions are actually being called.

When the `ERangeError` exception happens, doesn't Lazarus show you the code that raised it?

**Comment by abebuch** [comment] 2020-04-28 21:01
No. It is compiled with debug off, Otherwise it wont compile. It will complain that size is to big for WinCE.
![image](https://user-images.githubusercontent.com/6401040/80537284-c35a3480-8971-11ea-84cb-736d6ccb22db.png)

**Comment by rlebeau** [comment] 2020-04-29 02:51
The first time any Indy socket component is instantiated, it will create the `TIdStackWindows` object.  You are going to have to figure out how to step through that creation, or otherwise get your stack trace to show function names, in order for me to have any hope of finding the cause of the `ERangeError` exception.  Otherwise, there is nothing more I can do to help you.

**Comment by abebuch** [comment] 2020-04-29 15:35
This is what id in Idglobal.pas

function LoadLibFunction(const ALibHandle: TIdLibHandle; const AProcName: TIdLibFuncName): Pointer;
begin
showmessage('Going to call GetProcAddress');
  Result := {$IFDEF WINDOWS}Windows.{$ENDIF}GetProcAddress(ALibHandle, PIdLibFuncNameChar(AProcName));
showmessage('ended call to GetProcAddress');  //<--- never reaches 
end;

**Comment by rlebeau** [comment] 2020-04-29 21:43
There is a big comment about use of `TIdLibHandle` in `IdGlobal.pas`:
```
  // RLebeau 12/1/2018: FPC's System unit defines an HMODULE type as a PtrUInt. But,
  // the DynLibs unit defines its own HModule type that is a TLibHandle, which is a
  // PtrInt instead. And to make matters worse, although FPC's System.THandle is a
  // platform-dependant type, it is not always defined as 8 bytes on 64bit platforms,
  // which has been known to cause overflows when dynamic libraries are loaded at
  // high addresses! (FPC bug?)  So, we can't rely on THandle to hold correct handles
  // for libraries that we load dynamically at runtime (which is probably why FPC
  // defines TLibHandle in the first place, but why is it signed instead of unsigned?).
  //
  // Delphi's HMODULE is a System.THandle, which is a NativeUInt, and so is defined
  // with a proper byte size across all 32bit and 64bit platforms.
  //
  // Since (Safe)LoadLibrary(), GetProcAddress(), etc all use TLibHandle in FPC, but
  // use HMODULE in Delphi. this does mean we have a small descrepency between using
  // signed vs unsigned library handles.  I would prefer to use unsigned everywhere,
  // but we should use what is more natural for each compiler...

  // FPC's DynLibs unit is not included in this unit's interface 'uses' clause, only
  // in the implementation's 'uses' clause, so map to what DynLibs.TLibHandle maps to...
  TIdLibHandle = {$IFDEF FPC}{DynLibs.TLibHandle}PtrInt{$ELSE}THandle{$ENDIF};
```
However, for FPC on Windows, Indy calls `Windows.GetProcAddress()` directly and not `Dynlibs.GetProcAddress()`, so I wonder if that is causing the range error?  `Dynlibs.GetProcAddress()` uses `TLibHandle`, but `Windows.GetProcAddress()` uses `HINST` (`System.THandle`).

Oh wait, FPC defines `TLibHandle` as `THandle` on Windows, not as `PtrInt` as previously observed - ARG!!!

I have checked in an update for `IdGlobal.pas` to hopefully address this on Windows CE now.

**Comment by abebuch** [comment] 2020-04-29 23:05
Yep. Good now. Tried & tested.
Thanks a lot. Your the Best!

**Closed** 2020-04-30 00:18 UTC
Labels: Compiler, bug
