### ISSUE TITLE
Problem with compile under Delphi 7

### ISSUE THREAD

**Issue by jakmoy** [IndySockets/Indy#177] opened 2017-06-19 06:02 UTC
Latest version. Module "IdGlobalProtocols.pas". Function "GetUniqueFileName".
Delphi 7 compiler cannot handle compare TIdTicks type (Cardinal) with Int64.

Problem:
` if LTicks > High(Int64) then begin
    LTicks := High(Int64);
  end;`

Solution:
` if LTicks > TIdTicks(High(Int64)) then begin
    LTicks := TIdTicks(High(Int64));
  end;`

**Comment by rlebeau** [comment] 2017-06-19 19:27
TIdTicks is a UInt64.  In Delphi 7, UInt64 is an alias for Int64, not Cardinal (UInt64 became a distinct data type in Delphi 2006).  There should be no reason why the compiler cannot compare an Int64 to an Int64.

Unless you are saying that High(Int64) is the one returning a Cardinal?  I can't reproduce that.  High(Int64) returns 9223372036854775807, as expected. That can't fit in a Cardinal, but fits just fine in an Int64.

What is the EXACT compiler error you are getting?  When I copy/paste Indy's GetUniqueFileName() function and its supporting functions (Ticks64(), IndyDirectoryExists(), and IndyIncludeTrailingPathDelimiter()) as-is to a test project in Delphi 7, it compiles and runs just fine without having to make any changes to the code at all.  So the problem has to be on your end, not in Indy's code itself.

I did not try to compile the complete Indy packages in Delphi 7, but I doubt it would make a difference.  I don't think there is a compiler switch that would affect this.

**Comment by jakmoy** [comment] 2017-06-20 04:34
The exact error is:
`[Fatal Error] IdGlobalProtocols.pas(1663): Internat error: C1118`

I wrote "Cardinal", but of course I should write "UInt64".
This is **unsigned** Int64.
High(Int64) produces **signed** Int64.
The Delphi 7 compiler has a bug which cannot compile a code comparing two Int64 variables (a signed with unsigned one).
So, the simplest workaround is to tell Delphi 7 compiler that the two variables have the same types.
I did it with with simple cast TIdTicks().

**Comment by rlebeau** [comment] 2017-06-20 20:23
Internal errors are a compiler bug, not much to do about that except work around it.  But I still can't reproduce any errors when compiling GetUniqueFileName() as-is.  I'll have to try compiling the entire Indy when I have some free time.  And yes, I'm aware that High(Int64) produces a signed Int64.  That is perfectly fine.  Like I said, UInf64 is NOT an actual unsigned Int64 in Delphi 7, it is just an aliss for Int64.  So TIdTicks is a signed Int64 in Delphi 7.

**Comment by rlebeau** [comment] 2017-06-20 20:39
Fixed in SVN rev 5428

**Closed by rlebeau** 2017-06-20 20:39 UTC
