### ISSUE TITLE
Redesign TIdTCPClient connect with timeout without extra thread...

### ISSUE THREAD

**Issue by gec75** [IndySockets/Indy#466] opened 2023-04-25 09:34 UTC
I have an application where I need a very short connect timeout.
Then I just saw that Indy starts a new thread for this connect ...!?
I took the time to implement a version based on non blocking connect and select... see attached patch.
The idea is to split TIdSocketHandle.Connect into GStack.Connect (which starts an non-blocking connect) and later UpdateBinding.
The code in TIdIOHandlerStack.ConnectClient just starts connect then waits with select (write) and then decides to UpdateBinding or raise exception.
I also added the TIdSocketListWindows.SelectWrite... why was it not yet included??
It's just a prof of concept code, no AntiFreeze and no posix variant.

[indy_asyc_connect.patch](https://github.com/IndySockets/Indy/files/11321051/indy_asyc_connect.patch)

**Comment by rlebeau** [comment] 2023-04-25 17:15
Duplicate of #3.

I already have some code written for this feature (ultimately using a non-blocking `connect()` and handling the timeout via `select()`/`epoll()`, similarly to how you suggest, but taking a very different approach to the implementation to lessen changes to the existing interface).  That code hasn't been finished or even checked in yet.

Also, not every platform supports non-blocking sockets to begin with, so the connect thread can't be eliminated completely, but certainly avoided whenever possible.  The code I have queries the stack if non-blocking is supported, and if so then does the non-blocking `connect()`, otherwise uses the connect thread as before.

**Closed** 2023-04-26 00:47 UTC
Labels: Status: Duplicate, Type: Enhancement, Element: I/O Handlers, Element: Socket Stacks, Element: TCP
